/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#undef HAVE_MKDIRP

#define HAVE_STRNDUP

#define I3_VERSION "4.22 (2023-01-02)"

#define MAJOR_VERSION 4

#define MINOR_VERSION 22

#define PATCH_VERSION 0

#define SYSCONFDIR "/usr/local/etc"

